### ISSUE TITLE
Suggestion: Comment out "Serial" lines by default

### ISSUE THREAD

**Issue by gamecat69** [josbouten/Tune-O-Matic#4]
Great job on the code. One small suggestion is to have the following lines commented out by default. This may improve performance of the tuner slightly and would also stop the tx light from flashing constantly on the board.

```
Serial.begin(9600);
Serial.print(frequency);
Serial.println("hz 1 decimal place");
```

**Comment by josbouten** [comment]
Most of the code you are refering to is not in the current master. Maybe you could check out the code again?

**Comment by gamecat69** [comment]
You are correct. The lines I mentioned are in the version that Sam hosts on his website. [Here](https://www.lookmumnocomputer.com/s/TUNER_SKETCH_30.ino) is the link from his website.
